import type { Product } from "./types"

export const mockProducts: Product[] = [
  {
    id: "1",
    name: "Professional Claw Hammer",
    slug: "professional-claw-hammer",
    sku: "HAM-001",
    priceLKR: 4950,
    stock: 25,
    category: "Hammers",
    isActive: true,
    rating: 4.8,
    images: ["/images/products/hammer-claw-16oz.jpg"],
    specs: {
      Material: "Steel with rubber grip",
      Weight: "450g",
      Length: "32cm",
      Handle: "Anti-slip rubber",
    },
    description: "Heavy-duty claw hammer perfect for construction and carpentry work.",
    createdAt: "2024-01-15T10:30:00Z",
  },
  {
    id: "2",
    name: "Precision Screwdriver Set",
    slug: "precision-screwdriver-set",
    sku: "SCR-001",
    priceLKR: 2850,
    stock: 15,
    category: "Screwdrivers",
    isActive: true,
    rating: 4.6,
    images: ["/images/products/screwdriver-phillips-set.jpg"],
    specs: {
      Material: "Chrome vanadium steel",
      "Set Size": "12 pieces",
      Handle: "Ergonomic grip",
      Case: "Magnetic holder",
    },
    description: "Complete set of precision screwdrivers for detailed work.",
    createdAt: "2024-01-20T14:15:00Z",
  },
  {
    id: "3",
    name: "Adjustable Wrench 250mm",
    slug: "adjustable-wrench-250mm",
    sku: "WRE-001",
    priceLKR: 1850,
    stock: 8,
    category: "Wrenches",
    isActive: true,
    rating: 4.4,
    images: ["/images/products/wrench-adjustable-10inch.jpg"],
    specs: {
      Material: "Drop forged steel",
      Length: "250mm",
      "Jaw Capacity": "30mm",
      Finish: "Chrome plated",
    },
    description: "Durable adjustable wrench for various bolt sizes.",
    createdAt: "2024-02-01T09:45:00Z",
  },
  {
    id: "4",
    name: "Hand Saw 500mm",
    slug: "hand-saw-500mm",
    sku: "SAW-001",
    priceLKR: 3200,
    stock: 0,
    category: "Saws",
    isActive: true,
    rating: 4.7,
    images: ["/images/products/saw-hand-crosscut.jpg"],
    specs: {
      Material: "High carbon steel",
      Length: "500mm",
      TPI: "8 teeth per inch",
      Handle: "Hardwood grip",
    },
    description: "Sharp hand saw for precise wood cutting.",
    createdAt: "2024-02-10T16:20:00Z",
  },
  {
    id: "5",
    name: "Needle Nose Pliers",
    slug: "needle-nose-pliers",
    sku: "PLI-001",
    priceLKR: 1650,
    stock: 32,
    category: "Pliers",
    isActive: true,
    rating: 4.3,
    images: ["/images/products/pliers-needle-nose.jpg"],
    specs: {
      Material: "Chrome vanadium steel",
      Length: "200mm",
      "Jaw Type": "Serrated",
      Handle: "Cushion grip",
    },
    description: "Precision pliers for detailed electrical and mechanical work.",
    createdAt: "2024-02-15T11:10:00Z",
  },
  {
    id: "6",
    name: "Ball Peen Hammer",
    slug: "ball-peen-hammer",
    sku: "HAM-002",
    priceLKR: 3850,
    stock: 18,
    category: "Hammers",
    isActive: false,
    rating: 4.5,
    images: ["/images/products/hammer-ball-peen-12oz.jpg"],
    specs: {
      Material: "Forged steel head",
      Weight: "340g",
      Length: "28cm",
      Handle: "Hickory wood",
    },
    description: "Traditional ball peen hammer for metalworking.",
    createdAt: "2024-01-25T13:30:00Z",
  },
  {
    id: "7",
    name: "Phillips Head Screwdriver",
    slug: "phillips-head-screwdriver",
    sku: "SCR-002",
    priceLKR: 850,
    stock: 45,
    category: "Screwdrivers",
    isActive: true,
    rating: 4.2,
    images: ["/images/products/screwdriver-flathead-set.jpg"],
    specs: {
      Material: "Chrome vanadium steel",
      Size: "PH2",
      Length: "150mm",
      Handle: "Tri-material grip",
    },
    description: "Standard Phillips head screwdriver for general use.",
    createdAt: "2024-02-05T08:25:00Z",
  },
  {
    id: "8",
    name: "Combination Wrench Set",
    slug: "combination-wrench-set",
    sku: "WRE-002",
    priceLKR: 5650,
    stock: 12,
    category: "Wrenches",
    isActive: true,
    rating: 4.9,
    images: ["/images/products/wrench-combination-set.jpg"],
    specs: {
      Material: "Chrome vanadium steel",
      "Set Size": "8 pieces",
      Sizes: "8mm - 19mm",
      Finish: "Mirror polish",
    },
    description: "Complete set of combination wrenches in common sizes.",
    createdAt: "2024-01-30T15:40:00Z",
  },
  {
    id: "9",
    name: "Circular Saw Blade",
    slug: "circular-saw-blade",
    sku: "SAW-002",
    priceLKR: 2450,
    stock: 3,
    category: "Saws",
    isActive: true,
    rating: 4.6,
    images: ["/images/products/saw-hacksaw-frame.jpg"],
    specs: {
      Material: "Tungsten carbide",
      Diameter: "185mm",
      Bore: "20mm",
      Teeth: "40T",
    },
    description: "High-quality circular saw blade for wood cutting.",
    createdAt: "2024-02-12T12:55:00Z",
  },
  {
    id: "10",
    name: "Wire Stripping Pliers",
    slug: "wire-stripping-pliers",
    sku: "PLI-002",
    priceLKR: 2150,
    stock: 22,
    category: "Pliers",
    isActive: true,
    rating: 4.4,
    images: ["/images/products/pliers-wire-strippers.jpg"],
    specs: {
      Material: "Hardened steel",
      Length: "180mm",
      "Wire Range": "10-22 AWG",
      Handle: "Insulated grip",
    },
    description: "Professional wire stripping pliers for electrical work.",
    createdAt: "2024-02-18T10:15:00Z",
  },
  {
    id: "11",
    name: "Sledge Hammer 3kg",
    slug: "sledge-hammer-3kg",
    sku: "HAM-003",
    priceLKR: 6750,
    stock: 7,
    category: "Hammers",
    isActive: true,
    rating: 4.7,
    images: ["/images/products/hammer-claw-16oz.jpg"],
    specs: {
      Material: "Drop forged steel",
      Weight: "3kg",
      Length: "90cm",
      Handle: "Fiberglass",
    },
    description: "Heavy-duty sledge hammer for demolition work.",
    createdAt: "2024-02-20T14:30:00Z",
  },
  {
    id: "12",
    name: "Torx Screwdriver Set",
    slug: "torx-screwdriver-set",
    sku: "SCR-003",
    priceLKR: 3450,
    stock: 19,
    category: "Screwdrivers",
    isActive: true,
    rating: 4.5,
    images: ["/images/products/screwdriver-phillips-set.jpg"],
    specs: {
      Material: "S2 steel",
      "Set Size": "9 pieces",
      Sizes: "T10 - T50",
      Handle: "Magnetic tip",
    },
    description: "Professional Torx screwdriver set for automotive and electronics.",
    createdAt: "2024-02-22T09:20:00Z",
  },
]

export const categories = ["Hammers", "Screwdrivers", "Wrenches", "Saws", "Pliers"] as const
